apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleetsync.fullname" . }}-api
  labels:
    {{- include "fleetsync.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fleetsync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleetsync.fullname" . }}-control-center
  labels:
    {{- include "fleetsync.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-center
spec:
  type: {{ .Values.controlCenter.service.type }}
  ports:
    - port: {{ .Values.controlCenter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fleetsync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-center
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleetsync.fullname" . }}-mobile
  labels:
    {{- include "fleetsync.labels" . | nindent 4 }}
    app.kubernetes.io/component: mobile
spec:
  type: {{ .Values.mobile.service.type }}
  ports:
    - port: {{ .Values.mobile.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fleetsync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mobile
